name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build application
        run: npm run build
      - name: Deploy the application
        run: |
          # Your deployment commands here
          # For example, deploy to AWS, Heroku, etc.
          echo "Deploying application..."
      - name: Update deployment status to success
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.repos.createDeploymentStatus({
              owner: context.repo.owner,
              repo: context.repo.repo,
              deployment_id: DEPLOYMENT_ID,  # Replace with actual deployment ID if managing deployments
              state: 'success',
              environment_url: 'https://your-app-url.com',  # URL where app is deployed
              description: 'Deployment successful!',
            })
      
  trigger-ui-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test from another repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }} #this secret is added in triggering repo
          repository: thanhnhan262/webauto-playwright
          event-type: run-playwright-test
