name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the application
        run: |
          # Your deployment commands here
          # For example, deploy to AWS, Heroku, etc.
          echo "Deploying application..."
  trigger-ui-test:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Trigger test from another repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }} #this secret is added in triggering repo
          repository: thanhnhan262/webauto-playwright
          event-type: run-playwright-test
          client-payload: '{"app_url": "https://www.google.com/"}' # possiblly replace with url deploy job sends
